version: '3'

services:
  web:
    build: .
    container_name: backing_track_app
    restart: unless-stopped
    expose:
      - "8000"  # This is your gunicorn port
    volumes:
      - .:/app
      - ./static:/app/static  # Mount static files
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8080:80"  # External port mapping
    volumes:
      - ./static:/app/static  # Mount static files to nginx
    environment:
      - WORKER_PROCESSES=auto
      - WORKER_CONNECTIONS=1024
      - KEEPALIVE_TIMEOUT=65
      - CLIENT_MAX_BODY_SIZE=10M
      - LISTEN_PORT=80  # Nginx internal port
      - APP_PORT=8000  # Should match your gunicorn port
      - APP_HOST=web  # Should match your gunicorn port
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge